### ISSUE TITLE
AppProjectの命名を変更する

### ISSUE THREAD

**Issue by ophum** [ophum/kubernetes-practice-lab#6]
いま `app-team-project-*`でプロジェクトやApplicationを作成しているが冗長でわかりづらいことになっているので変更したい。

AppProject

sourceReposには任意のプロジェクトのリポジトリやorgを記述したい
```
kind: AppProject
apiVersion: argoproj.io/v1alpha1
metadata:
  name: <任意の名前>
  namespace: argocd
spec:
  sourceRepos:
  - '*'
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  destinations:
    - namespace: <任意の名前>-*
      server: https://kubernetes.default.svc
      name: in-cluster
  sourceNamespaces:
    - <任意の名前>
```

app of apps aplication

- 果たしてnamespaceが<任意の名前>でよいのかわかってない
  - argocdに入れたほうが良い?
```
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: <任意の名前>-apps
  namespace: <任意の名前>
spec:
  destination:
    namespace: app-team-project
    server: https://kubernetes.default.svc
  project: <任意の名前>
  source:
    path: <プロジェクトのアプリケーションがあるパス>
    repoURL: <プロジェクトのアプリケーションがあるリポジトリ>
  syncPolicy:
    automated: {}
    syncOptions:
    - CreateNamespace=true
```
